### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Raider1221** [benbenlaw/seaopolis#134]
Every time I load the game and try to launch it, it crashes. This is what the crash report says the problem is.  Version is Forge 36.2.2                                  -- Block entity being ticked --
Details:
	Name: exnihilosequentia:crucibles // novamachina.exnihilosequentia.common.tileentity.crucible.WoodCrucibleTile
	Block: Block{exnihilosequentia:crucible_wood}
	Block location: World: (5,134,9), Chunk: (at 5,8,9 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block: Block{exnihilosequentia:crucible_wood}
	Block location: World: (5,134,9), Chunk: (at 5,8,9 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Block Entity NBT: {x:5,y:134,ticksSinceLast:0,z:9,id:"exnihilosequentia:crucibles",inventory:{Size:1,Items:[],hasRoom:1b,type:"wood"},tank:{FluidName:"kubejs:organic_fluid",Amount:3450},currentItem:{id:"minecraft:oak_leaves",Count:1b},solidAmount:0}
Stacktrace:
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:advancedrocketry:coremodmethod,xf:fml:twilightforest:hitbox,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:APP:quark.mixins.json:ServerWorldMixin,pl:mixin:A}

**Comment by benbenlaw** [comment]
remove the wooden cruicle from the world using NBT editor for more help join the discord
https://discord.gg/f92STFGN32
