### ISSUE TITLE
Crash while joining world

### ISSUE THREAD

**Issue by EamonnDR** [benbenlaw/seaopolis#41]
Hey, I just started up the modpack, no issues, but when I wanted to join my world, my game crashed.
This is the crash part of the report:

[16:34:44] [Server thread/INFO]: Changing view distance to 11, from 10
[16:34:44] [Server thread/INFO]: The list of contributors has been loaded successfully
[16:34:44] [Server thread/INFO]: Using new advancement loading for net.minecraft.advancements.PlayerAdvancements@198e1075
[16:34:44] [Server thread/FATAL]: Preparing crash report with UUID 7a8dfe94-79bb-4534-9bf7-341ad7fca87e
[16:34:44] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$21976/337781023.run(Unknown Source) [?:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at novamachina.exnihilosequentia.common.tileentity.crucible.WoodCrucibleTile.func_73660_a(WoodCrucibleTile.java:42) ~[?:1.16-2.0.2.6]
	at net.minecraft.world.World.func_217391_K(World.java:491) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:371) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 6 more

Could someone please help me? Thanks a lot!!

**Comment by LotP1** [comment]
it's the wooden crucible ticking out the internal server.
it's a known bug and to fix it you have to edit the region file and remove the block manually from there.

**Comment by benbenlaw** [comment]
can you upload a copy of the effect world somewhere

**Comment by EamonnDR** [comment]
Where do i find those?

**Comment by benbenlaw** [comment]
best to be explained on discord haha

**Comment by EamonnDR** [comment]
I've sent u a dm

**Comment by Songahm** [comment]
I have run into this same issue, i tried deleting the crucible in a world edit but then all of my other modded blocks broke (drawers, tanks)
